spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diary?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: cho980625
    driver-class-name: com.mysql.cj.jdbc.Driver

  #페이징 처리 관련 --> 뭔지 알자
  #프론트 데이터 바인딩 카멜케이스대신.
  jackson:
    property-naming-strategy: SNAKE_CASE

  date:
    web:
      pageable:
        one-indexed-parameters: true

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        #???? ??? /* ??? ??? ????.
        use_sql_comments : true


logging.level:
  org.hibernate.SQL: debug

jwt:
  secret: AAAABBBBCCCCDDDDEEEEFFFFGGGG123!@#
