spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diary?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: cho980625
    driver-class-name: com.mysql.cj.jdbc.Driver

  date:
    web:
      pageable:
        one-indexed-parameters: true

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        #???? ??? /* ??? ??? ????.
        use_sql_comments : true


logging.level:
  org.hibernate.SQL: debug
